name: Matrix Strategy 1

on:
    workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [1.22, 1.21, 1.20]
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.version }}
      - run: go run sample_code/hello_world.go