name: on_tag_push

on:
  push:
    tags:
      - v*.*.*
      - test-*
      - release-*
      - on_tag_push-[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a tag push event."
      - run: echo "Tag name:${{ github.ref_name }}"