name: Run Parallel Go Code

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "/sample_code/parallel_run.go"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Workflow Message
        run: echo "Start Workflow"

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: run go
        run: go run sample_code/parallel_run.go Build 15

  TestA:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Start TestA Workflow Message
        run: echo "Start TestA Workflow"
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: run go
        run: go run sample_code/parallel_run.go TestA 12

  TestB:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Start TestB Workflow Message
        run: echo "Start TestB Workflow"
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: run go
        run: go run sample_code/parallel_run.go TestB 8

  Deploy:
    runs-on: ubuntu-latest
    needs: [Build, TestA, TestB]
    steps:
      - name: Start Deploy Workflow Message
        run: echo "Start Deploy Workflow"
    
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: run go
        run: go run sample_code/parallel_run.go Deploy 5

      - name: End Workflow Message
        run: echo "End Workflow"